version: '3.8'

services:
  app:
    image: php:7.3-apache
    container_name: php_app
    ports:
      - "1012:80"
    volumes:
      - ./public:/var/www/html
      - ./db:/var/www/db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: >
      bash -c "apt-get update &&
               apt-get install -y libsqlite3-dev &&
               docker-php-ext-install pdo_sqlite &&
               mkdir -p /var/www/db &&
               chmod -R 755 /var/www/html &&
               chown -R root:root /var/www/html &&
               chown -R www-data:www-data /var/www/db &&
               chmod -R 777 /var/www/db &&
               apache2-foreground"
